version: 1.0.{build}
image: Visual Studio 2017
skip_tags: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
build_script:
  - dotnet build -c Release
test_script:
  - dotnet test

after_test:
   - cmd: nuget install OpenCover -OutputDirectory packages -Version 4.7.922
   - cmd: packages\OpenCover.4.7.922\tools\OpenCover.Console.exe -register:user -filter:"+[DiscordBotCoreTut*]* -[DiscordBotCoreTut*]*Tests.*" -target:"packages\xunit.runner.console.2.4.1\tools\netcoreapp2.0\xunit.console.dll" -targetargs:"/noshadow /domain:single DiscordBotCoreTut.xUnit.Tests\bin\Release\netcoreapp2.0\DiscordBotCoreTut.xUnit.Tests.dll" -output:coverage.xml

   - cmd: packages.coveralls.io.1.4.2\tools\coveralls.net.exe --opencover coverage.xml -r %COVERALLS_REPO_TOKEN%