version: 1.0.{build}
image: Visual Studio 2019
skip_tags: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
build_script:
  - dotnet build -c Release
test_script:
  - dotnet test
 
after_test:
  - cmd: nuget install OpenCover -OutputDirectory packages -Version 4.7.922
  - cmd: .\packages\OpenCover.4.7.922\tools\OpenCover.Console.exe -register:user -target:"dotnet.exe" -targetargs:"DiscordBotCoreTut.xUnit.Tests\bin\Release\netcoreapp2.2\DiscordBotCoreTut.xUnit.Tests.dll -noshadow" -output:"coverage.xml" -filter:"+[DiscordBotCoreTut*]* -[DiscordBotCore*]*Tests.*" -oldstyle